apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: imagestore
  namespace: imagestore
  labels:
    app: imagestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagestore
  template:
    metadata:
      labels:
        app: imagestore
    spec:
      volumes:
        - name: imagestore-pv-storage
          persistentVolumeClaim:
            claimName: imagestore-pv-claim
      containers:
        - name: imagestore
          image: imagestore:1.0
          volumeMounts:
            - mountPath: "/usr/share/neo/"
              name: imagestore-pv-storage
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 500m


---

apiVersion: v1
kind: Service
metadata:
  name: imagestore-ser
  namespace: imagestore
  labels:
    app: imagestore
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: imagestore
