kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: imagestore-pv-claim
  namespace: imagestore
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Mi

