apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: imagestore-events
  namespace: imagestore
  labels:
    app: imagestore-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagestore-events
  template:
    metadata:
      labels:
        app: imagestore-events
    spec:
      containers:
        - name: imagestore-events
          image: imagestore-events:1.0
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 500m


---

apiVersion: v1
kind: Service
metadata:
  name: imagestoreevents-ser
  namespace: imagestore
  labels:
    app: imagestore-events
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    protocol: TCP
  selector:
    app: imagestore-events
